name: dsms
channels:
  - menpo
  - conda-forge
  - anaconda-fusion
  - defaults
dependencies:
  - ca-certificates=2018.11.29
  - certifi=2018.11.29
  - libcxx=7.0.0
  - libffi=3.2.1
  - llvm-meta=7.0.0
  - ncurses=6.1
  - openssl=1.0.2p
  - pip=19.0.1
  - python=2.7.15
  - readline=7.0
  - setuptools=40.7.1
  - sqlite=3.26.0
  - tk=8.6.9
  - wheel=0.32.3
  - zlib=1.2.11
  - pip:
    - bz2file==0.98
    - chardet==3.0.4
    - click==6.7
    - decorator==4.3.0
    - docutils==0.14
    - falcon==1.4.1
    - futures==3.2.0
    - gunicorn==19.7.1
    - idna==2.6
    - jmespath==0.9.3
    - pattern==2.6
    - python-dateutil==2.6.1
    - python-mimeparse==1.6.0
    - pytz==2018.4
    - requests==2.18.4
    - six==1.11.0
    - urllib3==1.22

